# SPDX-License-Identifier: Apache-2.0
# ODR Frontend Taskfile
version: 3

tasks:
  test:
    desc: Run unit and integration tests
    cmds:
      - task: test-unit
      - task: test-integration

  test-unit:
    desc: Run unit tests using vitest
    cmds:
      - docker compose exec odr-frontend pnpm test:unit

  test-integration:
    desc: Run integration tests using playwright
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run test:integration

  check:
    desc: Run svelte checks
    cmds:
      - pnpm run check
  check-watch:
    desc: Run svelte-checks and --watch
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run check:watch

  lint:
    desc: Run prettier checks and eslint
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run lint
  format:
    desc: Run prettier with the --write flag
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run format
