# SPDX-License-Identifier: Apache-2.0
# ODR Frontend Taskfile
version: 3

tasks:
  install:
    desc: Install npm dependencies
    dir: '{{.ROOT_DIR}}/modules/odr_frontend'
    cmds:
      - pnpm install
      - pnpm exec playwright install
  test:
    desc: Run unit and integration tests
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend test
  test-unit:
    desc: Run run unit-tests using vitest
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend test:unit
  test-integration:
    desc: Run integration tests using playwright
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run test:integration
  dev:
    desc: Run the frontend during development
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run dev
  check:
    desc: Run svelte checks
    cmds:
      - pnpm run check
  check-watch:
    desc: Run svelte-checks and --watch
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run check:watch
  build:
    desc: Build the frontend for deployment
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run build
  lint:
    desc: Run prettier checks and eslint
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run lint
  format:
    desc: Run prettier with the --write flag
    cmds:
      - pnpm -C {{.ROOT_DIR}}/modules/odr_frontend run format
