# aidriver_stores Taskfile
version: '3'
tasks:

  test:
    desc: Run tests for the core module
    cmds:
      - echo "Core module testing not implemented yet"

  test-db:
    desc: Run tests for the database manager
    cmds:
      - echo "Database manager testing not implemented yet"
