# aidriver_stores Taskfile
version: '3'
tasks:

  test:
    desc: Run tests for the core module
    cmds:
      - echo "Testing not implemented"

  test-db:
    desc: Run tests for the database manager
    cmds:
      - echo "Testing not implemented"
