# SPDX-License-Identifier: Apache-2.0
name: odr
services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PORT: 35432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 35432:5432
    networks:
      - omi-network

  odr-api:
    build:
      context: .
      dockerfile: modules/odr_api/docker/Dockerfile.api
    env_file:
      - .env
    ports:
      - "31100:31100"
    networks:
      - omi-network
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      ENVIRONMENT: DOCKER
    develop:
      watch:
        - action: sync
          path: ./modules/odr_core
          target: /app/modules/odr_core
        - action: sync
          path: ./modules/odr_api
          target: /app/modules/odr_api

  odr-frontend:
    build:
      context: .
      dockerfile: modules/odr_frontend/docker/Dockerfile.frontend.dev
    volumes:
      - ./modules/odr_frontend:/app
      - odr_frontend_node_modules:/app/node_modules
      - odr_frontend_pnpm_store:/app/.pnpm-store
      - ${UPLOAD_DIR:-./uploads}:/app/uploads
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      API_SERVICE_URL: http://odr-api:31100/api/v1
      UPLOAD_DIR: /app/uploads
      RUN_MIGRATIONS: ${RUN_MIGRATIONS:-false}
      VITE_GIT_BRANCH: ${VITE_GIT_BRANCH}
      VITE_GIT_COMMIT: ${VITE_GIT_COMMIT}
      VITE_BUILD_TIME: ${VITE_BUILD_TIME}
      VITE_APP_VERSION: ${VITE_APP_VERSION}
    env_file:
      - ./modules/odr_frontend/.env
    networks:
      - omi-network
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./modules/odr_frontend
          target: /app
          ignore:
            - node_modules/
            - .pnpm-store/
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
    entrypoint: /bin/sh -c "chmod 600 /pgpass; /entrypoint.sh;"
    user: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-35050}:80"
    networks:
      - omi-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
  odr_frontend_node_modules:
  odr_frontend_pnpm_store:

networks:
  omi-network:
    external: true
    driver: bridge
