FROM node:22-alpine

WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Install aws-cli
RUN apk add --no-cache aws-cli

# Install s3fs-fuse for mounting S3 bucket, remove if using mount point
RUN apk add --no-cache s3fs-fuse

# Prepare for the AWS
RUN mkdir -p /mnt/upload
RUN mkdir -p /mnt/models

# Copy package.json and pnpm-lock.yaml (if you have one)
COPY package.json pnpm-lock.yaml* ./

# Copy the entrypoint script
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY .env.template /app/.env

EXPOSE 5173

ENTRYPOINT ["/entrypoint.sh"]

CMD ["pnpm", "run", "dev", "--", "--host", "0.0.0.0"]
