"""'create feature toggles table and insert initial toggles'

Revision ID: 2f2d84a873f5
Revises: e06f931c3c84
Create Date: 2024-10-06 13:19:19.864205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2d84a873f5'
down_revision: Union[str, None] = 'e06f931c3c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'feature_toggles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('feature_name', sa.String(length=255), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False),
        sa.Column('default_state', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('feature_name')
    )

    # Insert initial feature toggles
    op.bulk_insert(
        sa.table(
            'feature_toggles',
            sa.Column('feature_name', sa.String(length=255)),
            sa.Column('is_enabled', sa.Boolean()),
            sa.Column('default_state', sa.Boolean())
        ),
        [
            {'feature_name': 'HDR Image Upload', 'is_enabled': True, 'default_state': True},
            {'feature_name': 'Show Datasets', 'is_enabled': False, 'default_state': False},
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feature_toggles')
    # ### end Alembic commands ###
