# SPDX-License-Identifier: Apache-2.0
"""'Add updated_at fields for annotations'

Revision ID: 3513a015e114
Revises: d109dc6c5755
Create Date: 2024-08-18 06:34:32.774565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3513a015e114'
down_revision: Union[str, None] = 'd109dc6c5755'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation_ratings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('annotation_reports', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotation_reports', 'updated_at')
    op.drop_column('annotation_ratings', 'updated_at')
    # ### end Alembic commands ###
