# SPDX-License-Identifier: Apache-2.0
"""'Add constraints to embeddings'

Revision ID: 4f394aae9708
Revises: 1f34b3b4b87c
Create Date: 2024-08-08 13:47:31.251740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f394aae9708'
down_revision: Union[str, None] = '1f34b3b4b87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ic_annotation_embedding_engine', 'annotation_embeddings', ['annotation_id', 'embedding_engine_id'])
    op.create_unique_constraint('ic_content_embedding_engine', 'content_embeddings', ['content_id', 'embedding_engine_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ic_content_embedding_engine', 'content_embeddings', type_='unique')
    op.drop_constraint('ic_annotation_embedding_engine', 'annotation_embeddings', type_='unique')
    # ### end Alembic commands ###
