# SPDX-License-Identifier: Apache-2.0
"""Add team-user relationship

Revision ID: 6f85df1a1521
Revises: e5647515ed8d
Create Date: 2024-07-20 12:53:14.625640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f85df1a1521'
down_revision: Union[str, None] = 'e5647515ed8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
