"""'Remove usertype'

Revision ID: bef5de2052d7
Revises: 31ba65eb76f9
Create Date: 2024-10-31 21:51:42.770404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bef5de2052d7'
down_revision: Union[str, None] = '31ba65eb76f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', postgresql.ENUM('user', 'bot', name='usertype'), server_default=sa.text("'user'::usertype"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
