# SPDX-License-Identifier: Apache-2.0
"""Add content relations

Revision ID: d712027f6e8b
Revises: ddb9c9a9ecce
Create Date: 2024-07-20 14:02:24.231327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd712027f6e8b'
down_revision: Union[str, None] = 'ddb9c9a9ecce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
