# SPDX-License-Identifier: Apache-2.0
"""Add Content and ContentAuthor tables

Revision ID: ddb9c9a9ecce
Revises: 6f85df1a1521
Create Date: 2024-07-20 13:13:23.079117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb9c9a9ecce'
down_revision: Union[str, None] = '6f85df1a1521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'contents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('type', sa.Enum('IMAGE', 'VIDEO', 'VOICE', 'MUSIC', 'TEXT', name='contenttype'), nullable=True),
        sa.Column('hash', sa.String(), nullable=True),
        sa.Column('phash', sa.String(), nullable=True),
        sa.Column('url', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('format', sa.String(), nullable=True),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'AVAILABLE', 'UNAVAILABLE', 'DELISTED', name='contentstatus'), nullable=True),
        sa.Column('license', sa.String(), nullable=True),
        sa.Column('license_url', sa.String(), nullable=True),
        sa.Column('flags', sa.Integer(), nullable=True),
        sa.Column('meta', sa.JSON(), nullable=True),
        sa.Column('from_user_id', sa.Integer(), nullable=True),
        sa.Column('from_team_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
        sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_hash'), 'contents', ['hash'], unique=False)
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_phash'), 'contents', ['phash'], unique=False)
    op.create_table(
        'content_authors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('content_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_authors_id'), 'content_authors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_authors_id'), table_name='content_authors')
    op.drop_table('content_authors')
    op.drop_index(op.f('ix_contents_phash'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_hash'), table_name='contents')
    op.drop_table('contents')
    # ### end Alembic commands ###
