"""'Update users table to have non nullable and default values for flags'

Revision ID: e06f931c3c84
Revises: 6917b71d9140
Create Date: 2024-10-03 18:14:20.255813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06f931c3c84'
down_revision: Union[str, None] = '6917b71d9140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Update existing null values to their default values
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE users SET is_superuser = false WHERE is_superuser IS NULL")
    op.execute("UPDATE users SET dco_accepted = false WHERE dco_accepted IS NULL")

    op.alter_column('users', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    server_default=sa.text('true'))
    op.alter_column('users', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    server_default=sa.text('false'))
    op.alter_column('users', 'dco_accepted',
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                    server_default=sa.text('false'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dco_accepted',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    server_default=sa.text('false'))
    op.alter_column('users', 'is_superuser',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
                    existing_type=sa.BOOLEAN(),
                    nullable=True,
                    server_default=sa.text('true'))
    # ### end Alembic commands ###
