from models.annotation.test_annotation_lifecycle import TestAnnotationLifecycle
from models.annotation.test_annotation_source_lifecycle import TestAnnotationSourceLifecycle
from models.annotation.test_annotation_rating_lifecycle import TestAnnotationRatingLifecycle
