name: odr-caption
services:
  caption:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.caption
    ports:
      - 32100:32100
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${HF_HOME}:/models
      - ../odr_caption:/app/odr_caption
      - ../local/cache:/root/.cache/
    environment:
      - HF_HOME=/models
    develop:
      watch:
        - action: sync
          path: ..
          target: /app
