# SPDX-License-Identifier: Apache-2.0
name: odr-caption
services:
  caption:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.caption
    user: "${UID:-1000}:${GID:-1000}"
    ports:
      - 32100:32100
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ${HF_HOME:-~/.cache}:/cache/HF_HOME
      - ../local/cache:/cache/local_cache
    environment:
      - HF_HOME=/cache/HF_HOME
      - ODR_TEXT_MODEL=${ODR_TEXT_MODEL:-Qwen/Qwen2.5-14B-Instruct-GPTQ-Int8}
      - ODR_VISION_MODEL=${ODR_VISION_MODEL:-mistral-community/pixtral-12b}
    develop:
      watch:
        - action: sync
          path: ../odr_caption
          target: /app/odr_caption
