FROM vllm/vllm-openai:v0.6.4.post1


ENV VLLM_VERSION=v0.6.4.post1
ENV DO_NOT_TRACK=1
# Install dependencies
COPY ./requirements.txt /app/requirements.txt

# Copy application code
COPY . /app
RUN pip3 install --no-cache-dir -e /app \
    && pip3 install git+https://github.com/dottxt-ai/outlines --upgrade

# Set Python path to include the modules
ENV PYTHONPATH=/app:/app/modules:$PYTHONPATH

# Expose the port the app runs on
EXPOSE 32100

COPY --chmod=775 endpoints-entrypoint.sh entrypoint.sh

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]
CMD ["tail", "-f", "/dev/null"]
