# SPDX-License-Identifier: Apache-2.0
# aidriver_stores Taskfile
version: '3'
tasks:

  migrate:
    desc: Migrate the database
    cmds:
      - alembic -c ./modules/odr_datamodel/alembic.ini upgrade head
    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 35432

  revision:
    desc: Create a new revision, e.g. task data:revision -- "Add new column"
    cmds:
      - alembic -c ./modules/odr_datamodel/alembic.ini revision --autogenerate -m "{{.CLI_ARGS}}"

  downgrade:
    desc: Downgrade the database
    cmds:
      - alembic -c ./modules/odr_datamodel/alembic.ini downgrade -1
