from odr_api.api.endpoints.annotation import router as annotation_router
from odr_api.api.endpoints.content import router as content_router
from odr_api.api.endpoints.embedding import router as embedding_router
from odr_api.api.endpoints.team import router as team_router
from odr_api.api.endpoints.user import router as user_router
from odr_api.api.endpoints.auth import router as auth_router
from odr_api.api.endpoints.health import router as health_router
from odr_api.api.endpoints.image import router as image_router
from odr_api.api.endpoints.hugging_face import router as hugging_face_router
