version: 3

tasks:
  test:
    desc: Run tests for the api server
    cmds:
      - python -m pytest -v ${ROOT_DIR}/modules/odr_api/tests/test_user_api.py
  start: 
    desc: Start the api server
    cmds:
     # - powershell.exe -ExecutionPolicy ByPass -File ${ROOT_DIR}/modules/odr_api/server/scripts/run_server.ps1
     - echo 'Start server stub'