# SPDX-License-Identifier: Apache-2.0
name: Check SPDX License Identifiers

on:
  pull_request:
    branches: [ main ]

jobs:
  check-spdx:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit

    - name: Run pre-commit
      run: pre-commit run check-spdx-license --all-files

    - name: Check for missing SPDX identifiers
      if: failure()
      run: |
        echo "::error::Some files are missing SPDX license identifiers. Please add them."
        exit 1
