# SPDX-License-Identifier: Apache-2.0
# .github/workflows/documentation.yml
# -----------------------------------------------------------------------------

name: documentation
on:
  workflow_dispatch:
  push:
    branches: [ "main", "doc_sandbox"]
    paths:
      - 'doc/**'
      - '.github/workflows/documentation.yml'

permissions:
    pages: write
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx pydata-sphinx-theme myst_parser
      - name: Sphinx build
        run: |
          sphinx-build doc _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/doc_sandbox') }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
