# SPDX-License-Identifier: Apache-2.0
name: Publish Caption Service

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  CAPTION_IMAGE_NAME: ${{ github.repository }}/odr-caption

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.7.0
        with:
          cosign-release: 'v2.4.1'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Caption Docker metadata
        id: meta-caption
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.CAPTION_IMAGE_NAME }}

      - name: Build and push Caption Docker image
        id: build-and-push-caption
        uses: docker/build-push-action@v6
        with:
          context: ./modules/odr_caption
          file: ./modules/odr_caption/docker/Dockerfile.caption
          # push: ${{ github.event_name != 'pull_request' }}
          push: true
          tags: ${{ steps.meta-caption.outputs.tags }}
          labels: ${{ steps.meta-caption.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Caption Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          TAGS: ${{ steps.meta-caption.outputs.tags }}
          DIGEST: ${{ steps.build-and-push-caption.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
