# SPDX-License-Identifier: Apache-2.0
name: Database Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/odr_database/**'
      - '.github/workflows/db-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/odr_database/**'
      - '.github/workflows/db-tests.yml'

jobs:
  postgres-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: opendatarepository
          POSTGRES_USER: opendatarepository
          POSTGRES_PASSWORD: opendatarepository
        ports:
          - 35432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest psycopg2-binary

    - name: Run database connection tests
      run: |
        pytest -v modules/odr_database/tests/test_db_connection.py
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 35432
        POSTGRES_DB: opendatarepository
        POSTGRES_USER: opendatarepository
        POSTGRES_PASSWORD: opendatarepository
