# SPDX-License-Identifier: Apache-2.0
name: Core Module Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/odr_core/**'
      - '.github/workflows/core-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/odr_core/**'
      - '.github/workflows/core-tests.yml'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/odr_core

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov

    - name: Run unit tests with coverage
      run: |
        pytest --cov=odr_core tests/unit/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: core-unit
        name: core-module-unit
        fail_ci_if_error: true

  integration-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/odr_core

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: opendatarepository
          POSTGRES_USER: opendatarepository
          POSTGRES_PASSWORD: opendatarepository
        ports:
          - 35432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov

    - name: Run integration tests with coverage
      run: |
        pytest --cov=odr_core tests/integration/ --cov-report=xml
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 35432
        POSTGRES_DB: opendatarepository
        POSTGRES_USER: opendatarepository
        POSTGRES_PASSWORD: opendatarepository

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: core-integration
        name: core-module-integration
        fail_ci_if_error: true
