# SPDX-License-Identifier: Apache-2.0
name: Monitoring Module Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'modules/odr_monitoring/**'
      - '.github/workflows/monitoring-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'modules/odr_monitoring/**'
      - '.github/workflows/monitoring-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./modules/odr_monitoring

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov

    - name: Run tests with coverage
      run: |
        pytest --cov=odr_monitoring tests/ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: monitoring
        name: monitoring-module
        fail_ci_if_error: true
